name: Feature Request
description: Suggest a new feature or enhancement for PixelFlasher
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        # PixelFlasher Feature Request
        Thank you for taking the time to suggest a feature for PixelFlasher.

        Please ensure your feature request is not already covered in existing issues.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you've completed these steps before submitting your feature request.
      options:
        - label: I have searched existing issues to make sure this feature has not been requested before
          required: true
        - label: I have searched the [XDA Forums](https://xdaforums.com/t/pixelflasher-a-gui-tool-for-flashing-updating-rooting-managing-pixel-phones.4415453/) to make sure this feature has not been requested before
          required: true
        - label: I have read the README documentation to confirm this feature doesn't already exist
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also thought about [...]

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here
